services:
  drupal:
    build:
      context: .
      dockerfile: docker/drupal/dev/php/Dockerfile
    ports:
      - 8200:80
    working_dir: /app/public/drupal
    volumes:
      - .:/app/public
      - ./docker/drupal/dev/caddy/Caddyfile:/etc/frankenphp/Caddyfile
      - ./docker/drupal/dev/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - chloecorfmat-network
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chloecorfmat_v2.rule=Host(`chloecorfmat.fr`)"
      - "traefik.http.routers.chloecorfmat_v2.entrypoints=websecure"
      - "traefik.http.routers.chloecorfmat_v2.middlewares=strip-www"
      # Middleware de redirection
      - "traefik.http.middlewares.redirect-old-blog.redirectregex.regex=^https?://([^/]+)/blog/2024/08/liens-evitement/?$$"
      - "traefik.http.middlewares.redirect-old-blog.redirectregex.replacement=https://$${1}/liens-evitement"
      - "traefik.http.middlewares.redirect-old-blog.redirectregex.permanent=true"

  db:
    image: postgres:16-bookworm
    command: -c 'max_connections=10'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=drupal
      - POSTGRES_USER=drupal
      - POSTGRES_PASSWORD=drupal
    networks:
      - chloecorfmat-network

volumes:
  db-data:

networks:
  chloecorfmat-network:
  web:
    external: true